// Generated by gencpp from file riki_msgs/Bluetooth.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_BLUETOOTH_H
#define RIKI_MSGS_MESSAGE_BLUETOOTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Bluetooth_
{
  typedef Bluetooth_<ContainerAllocator> Type;

  Bluetooth_()
    : connect_stats(0)
    , angle_x(0)
    , angle_y(0)  {
    }
  Bluetooth_(const ContainerAllocator& _alloc)
    : connect_stats(0)
    , angle_x(0)
    , angle_y(0)  {
  (void)_alloc;
    }



   typedef int32_t _connect_stats_type;
  _connect_stats_type connect_stats;

   typedef int32_t _angle_x_type;
  _angle_x_type angle_x;

   typedef int32_t _angle_y_type;
  _angle_y_type angle_y;





  typedef boost::shared_ptr< ::riki_msgs::Bluetooth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Bluetooth_<ContainerAllocator> const> ConstPtr;

}; // struct Bluetooth_

typedef ::riki_msgs::Bluetooth_<std::allocator<void> > Bluetooth;

typedef boost::shared_ptr< ::riki_msgs::Bluetooth > BluetoothPtr;
typedef boost::shared_ptr< ::riki_msgs::Bluetooth const> BluetoothConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Bluetooth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Bluetooth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::riki_msgs::Bluetooth_<ContainerAllocator1> & lhs, const ::riki_msgs::Bluetooth_<ContainerAllocator2> & rhs)
{
  return lhs.connect_stats == rhs.connect_stats &&
    lhs.angle_x == rhs.angle_x &&
    lhs.angle_y == rhs.angle_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::riki_msgs::Bluetooth_<ContainerAllocator1> & lhs, const ::riki_msgs::Bluetooth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Bluetooth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Bluetooth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Bluetooth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Bluetooth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Bluetooth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Bluetooth_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Bluetooth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d231f5dc5332675e1ab8a685bdfd06a0";
  }

  static const char* value(const ::riki_msgs::Bluetooth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd231f5dc5332675eULL;
  static const uint64_t static_value2 = 0x1ab8a685bdfd06a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Bluetooth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Bluetooth";
  }

  static const char* value(const ::riki_msgs::Bluetooth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Bluetooth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 connect_stats\n"
"int32 angle_x\n"
"int32 angle_y\n"
;
  }

  static const char* value(const ::riki_msgs::Bluetooth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Bluetooth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connect_stats);
      stream.next(m.angle_x);
      stream.next(m.angle_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bluetooth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Bluetooth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Bluetooth_<ContainerAllocator>& v)
  {
    s << indent << "connect_stats: ";
    Printer<int32_t>::stream(s, indent + "  ", v.connect_stats);
    s << indent << "angle_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle_x);
    s << indent << "angle_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_BLUETOOTH_H
