// Generated by gencpp from file riki_msgs/FaceVoiceSetRequest.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_FACEVOICESETREQUEST_H
#define RIKI_MSGS_MESSAGE_FACEVOICESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct FaceVoiceSetRequest_
{
  typedef FaceVoiceSetRequest_<ContainerAllocator> Type;

  FaceVoiceSetRequest_()
    : voice_id(0)  {
    }
  FaceVoiceSetRequest_(const ContainerAllocator& _alloc)
    : voice_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _voice_id_type;
  _voice_id_type voice_id;





  typedef boost::shared_ptr< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceVoiceSetRequest_

typedef ::riki_msgs::FaceVoiceSetRequest_<std::allocator<void> > FaceVoiceSetRequest;

typedef boost::shared_ptr< ::riki_msgs::FaceVoiceSetRequest > FaceVoiceSetRequestPtr;
typedef boost::shared_ptr< ::riki_msgs::FaceVoiceSetRequest const> FaceVoiceSetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator1> & lhs, const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.voice_id == rhs.voice_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator1> & lhs, const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98325de2d7d0e1dc65e6817d659bf621";
  }

  static const char* value(const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98325de2d7d0e1dcULL;
  static const uint64_t static_value2 = 0x65e6817d659bf621ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/FaceVoiceSetRequest";
  }

  static const char* value(const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 voice_id\n"
;
  }

  static const char* value(const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceVoiceSetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::FaceVoiceSetRequest_<ContainerAllocator>& v)
  {
    s << indent << "voice_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.voice_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_FACEVOICESETREQUEST_H
