// Generated by gencpp from file riki_msgs/FaceVoiceSet.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_FACEVOICESET_H
#define RIKI_MSGS_MESSAGE_FACEVOICESET_H

#include <ros/service_traits.h>


#include <riki_msgs/FaceVoiceSetRequest.h>
#include <riki_msgs/FaceVoiceSetResponse.h>


namespace riki_msgs
{

struct FaceVoiceSet
{

typedef FaceVoiceSetRequest Request;
typedef FaceVoiceSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceVoiceSet
} // namespace riki_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::riki_msgs::FaceVoiceSet > {
  static const char* value()
  {
    return "90941b667b08b1366244be00f14ce2ac";
  }

  static const char* value(const ::riki_msgs::FaceVoiceSet&) { return value(); }
};

template<>
struct DataType< ::riki_msgs::FaceVoiceSet > {
  static const char* value()
  {
    return "riki_msgs/FaceVoiceSet";
  }

  static const char* value(const ::riki_msgs::FaceVoiceSet&) { return value(); }
};


// service_traits::MD5Sum< ::riki_msgs::FaceVoiceSetRequest> should match
// service_traits::MD5Sum< ::riki_msgs::FaceVoiceSet >
template<>
struct MD5Sum< ::riki_msgs::FaceVoiceSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::riki_msgs::FaceVoiceSet >::value();
  }
  static const char* value(const ::riki_msgs::FaceVoiceSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::riki_msgs::FaceVoiceSetRequest> should match
// service_traits::DataType< ::riki_msgs::FaceVoiceSet >
template<>
struct DataType< ::riki_msgs::FaceVoiceSetRequest>
{
  static const char* value()
  {
    return DataType< ::riki_msgs::FaceVoiceSet >::value();
  }
  static const char* value(const ::riki_msgs::FaceVoiceSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::riki_msgs::FaceVoiceSetResponse> should match
// service_traits::MD5Sum< ::riki_msgs::FaceVoiceSet >
template<>
struct MD5Sum< ::riki_msgs::FaceVoiceSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::riki_msgs::FaceVoiceSet >::value();
  }
  static const char* value(const ::riki_msgs::FaceVoiceSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::riki_msgs::FaceVoiceSetResponse> should match
// service_traits::DataType< ::riki_msgs::FaceVoiceSet >
template<>
struct DataType< ::riki_msgs::FaceVoiceSetResponse>
{
  static const char* value()
  {
    return DataType< ::riki_msgs::FaceVoiceSet >::value();
  }
  static const char* value(const ::riki_msgs::FaceVoiceSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_FACEVOICESET_H
