// Generated by gencpp from file riki_msgs/PoseResponse.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_POSERESPONSE_H
#define RIKI_MSGS_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct PoseResponse_
{
  typedef PoseResponse_<ContainerAllocator> Type;

  PoseResponse_()
    {
    }
  PoseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::riki_msgs::PoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::PoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseResponse_

typedef ::riki_msgs::PoseResponse_<std::allocator<void> > PoseResponse;

typedef boost::shared_ptr< ::riki_msgs::PoseResponse > PoseResponsePtr;
typedef boost::shared_ptr< ::riki_msgs::PoseResponse const> PoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::PoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::PoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::PoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::PoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::riki_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/PoseResponse";
  }

  static const char* value(const ::riki_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::riki_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::PoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::PoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::riki_msgs::PoseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_POSERESPONSE_H
