// Generated by gencpp from file riki_msgs/RobotVoiceCtrlRequest.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_ROBOTVOICECTRLREQUEST_H
#define RIKI_MSGS_MESSAGE_ROBOTVOICECTRLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct RobotVoiceCtrlRequest_
{
  typedef RobotVoiceCtrlRequest_<ContainerAllocator> Type;

  RobotVoiceCtrlRequest_()
    : ctrl_id(0)  {
    }
  RobotVoiceCtrlRequest_(const ContainerAllocator& _alloc)
    : ctrl_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _ctrl_id_type;
  _ctrl_id_type ctrl_id;





  typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotVoiceCtrlRequest_

typedef ::riki_msgs::RobotVoiceCtrlRequest_<std::allocator<void> > RobotVoiceCtrlRequest;

typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlRequest > RobotVoiceCtrlRequestPtr;
typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlRequest const> RobotVoiceCtrlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator1> & lhs, const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_id == rhs.ctrl_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator1> & lhs, const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11f6f9365c6a32e4d7e2a5c7cc4c8895";
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11f6f9365c6a32e4ULL;
  static const uint64_t static_value2 = 0xd7e2a5c7cc4c8895ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/RobotVoiceCtrlRequest";
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ctrl_id\n"
;
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotVoiceCtrlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::RobotVoiceCtrlRequest_<ContainerAllocator>& v)
  {
    s << indent << "ctrl_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ctrl_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_ROBOTVOICECTRLREQUEST_H
