// Generated by gencpp from file riki_msgs/RobotVoiceCtrlResponse.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_ROBOTVOICECTRLRESPONSE_H
#define RIKI_MSGS_MESSAGE_ROBOTVOICECTRLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct RobotVoiceCtrlResponse_
{
  typedef RobotVoiceCtrlResponse_<ContainerAllocator> Type;

  RobotVoiceCtrlResponse_()
    : face_id(false)  {
    }
  RobotVoiceCtrlResponse_(const ContainerAllocator& _alloc)
    : face_id(false)  {
  (void)_alloc;
    }



   typedef uint8_t _face_id_type;
  _face_id_type face_id;





  typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotVoiceCtrlResponse_

typedef ::riki_msgs::RobotVoiceCtrlResponse_<std::allocator<void> > RobotVoiceCtrlResponse;

typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlResponse > RobotVoiceCtrlResponsePtr;
typedef boost::shared_ptr< ::riki_msgs::RobotVoiceCtrlResponse const> RobotVoiceCtrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator1> & lhs, const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.face_id == rhs.face_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator1> & lhs, const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "337f2aabe2cbd4bf896f44421c3c0179";
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x337f2aabe2cbd4bfULL;
  static const uint64_t static_value2 = 0x896f44421c3c0179ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/RobotVoiceCtrlResponse";
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool face_id\n"
"\n"
"\n"
;
  }

  static const char* value(const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.face_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotVoiceCtrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::RobotVoiceCtrlResponse_<ContainerAllocator>& v)
  {
    s << indent << "face_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.face_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_ROBOTVOICECTRLRESPONSE_H
